# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  GCS_BUCKET: spark_streaming_kafka_bq
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Echo
      run: |-
            echo spark_streaming_kafka_bq

    - name: Setup - gcloud / gsutil
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiYXZlbnVlY29kZS1wbGF5Z3JvdW5kIiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiOGUwY2ZjYmRiZmEzMzY4YzU1NzE2MDY4NmNkYjJkZDc3YTU2ODI2MiIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZ3SUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2t3Z2dTbEFnRUFBb0lCQVFEY09jK0RMRlFmL2YrUVxuMHF3REVIM0U1eGxpbittdDlYaFA1NTdvZEhIM1hKdTYvUUZXRlV2MkIwSDNFazlKdWphOU1GUlhDMGxvVTl4YVxuY2NXZXBZSkZkbEt1YmFoVUVpUmxERHZtRVlMYTRZbGd3UjJ3MWNoSjhMZ1BXWit3S2duZXNBNC9MNWNsemQ5L1xuUjRWTDl6VUxUYVRTc3lkd1pNYmlVZWozVGxUaXQxYzZyVGg0SExDcWhrZTQ2RHdOYkxQck5nU0g3RTlhQmVPNlxud1AzODZCM082VXl1R2M4OXNscFd5a09CSXdXUGkwcGo2Q2llVVBnSXpjZTF2bVEzbVlHcHpXWmFoTy9YVzZmeFxud3hYWXpwT0IzeThUU1lTZWQ5TlZDRVZoRUJ4VWJ3SktaZnVScVpjQm5kTU5FSWFZNkR6VlJXalAwV3dxZ1ZyelxuTGF3dkhwMTFBZ01CQUFFQ2dnRUFJSzVOanFROTZhOTZSUVlXYzYvM1VnaVBlbFRMeXo1eHQ3M2lGWkh1TmF5ZlxuQ1oweEhSSzAvcEl1SmxtbnZZT3VTdDRJcmhBbE9SKzB4QkU5SitGYzF5MExjUW9oNERQL0JhWE9uOEk2Zm52WVxudEt5RDJQR29zdHhQbkN1TEtJdmNnaGp6VEVvbUxueUNMYk94NHNlUkxoZThIVzVyckdDd0tQYkowU1ZsTUcySlxuTm9XVnRaTTFWTm4zeU93MUk4bVZ5QzBUeU1NRUtxVlp6a05INXQvM0xWaFBGWitPOW1aeGpOc0tPcGhISXI3aVxubzB6RFgxOHBnd1hyRTMxUGp5dHcvTmdaWkhSb1lkMGVoSEpubmlaQ2RmRUczeWtmTDRYR0xBMXVCdWd3L0Vmb1xuZEQyc1FlUjlIL3lMZmM5RThwMW9NSHZnYmM3eHNyRExncktPdDJUUFFRS0JnUUQyRVA1b1FIbytXNjJYWDE5clxuSFFUOWZia1huRjZCUXdBbDFCbjYrakNKNU9UOGIwa242UnFFTmtWZGZySy91Lzg1UEZXcmVENmVOUysra1o3SFxuN0lHbklYbEJQRldRV1dSYk0vTG9aZS9ScXZ3N0J1dWtkc0h6L0ZqZC9JVEEzMjNpU3E4Yk84N2RBU0NOSUNDWVxub1VNNFFuc0RtQnB4c3ZzMTd1cGgzeUN1bFFLQmdRRGxIY09hSWloVFV5UnRyWGJQVldLOFhxVlJoM2U0Nkw4MlxuTitobjQwQ0JuL3dySWVIL2VQeU1QcklRMVRDZVpyQ05tazA2ekpaVjBoc0o5YVFOR1dJTmd3Vzhyb2V3Z1hlRlxuSXNNaURMUFBIU1JLY25qWTNDY1JSWThrdkRTMHkraytoM1RZb21GNHBNYnYrUnJEUXhhLzVwWXpOb3YzbUJ5TFxuMzBxQlF4ZmJZUUtCZ1FESXdtaXU2aHhTa0QzN1NNYnkvNFE0eGNDajhPSnlHQllneHdKRGNLajFlSmtURkVEZFxublNRVFJxd2xjZCtvNjF0NmVTMTBidkMzNTdFQ2pKQzlrTXJmYjBJYzVYcnlBTjBPUkQ0bE9qWUdITGtaOTdWK1xuUTU1TzBFNDVIM080WVJLb0ZFTDF0MEE1dEZlNGpNUExnNWJ5YWRzdnZZT2x6RitGUzE1VFo5YWtXUUtCZ1FDOFxub1JpZEdXb2h6OTI1L29wR2dJSGRtLzUzZFJSNFJBYkkySmFha1ZwV1hpVDZUZGNHd2RFS2xjTjhZRWk2NE1pU1xuakdydzhlY0RtUXR4MDY3UXFnazBIcDdtakxwaDh2VTN3enJzR1pFZi8xb1ZnTkZGbVZzQXVVZjBjbzdpR3M5WlxuRDZSL2hwREJCc2hTWWNCSzZqMGNtUGNvQ3N5SmQ4NW95ZGxKT3JlMWdRS0JnUURubjNvM1NFeHVrdTVhZHdjcVxuY09jbVorUlF2UGdFbFBTS0xaVTNITW4ycW9MNEE1eko3cHdrbnErR014K0FxNHBpK0trSkFXNndzcEZQWHB5U1xuZW1EK2V6dWcrNTJoSE5FVmwzUlJ5ZUE5ajlwc2d1ZnFjMll5SVFqRXFTdmExMm5ZekRnLzNlbEZLbGN6VkVRMVxuckJyOFNyMHNpSmorTCtETGRvUVV5RXFCOXc9PVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogImdpdGh1YmNpY2R0ZXN0ZUBhdmVudWVjb2RlLXBsYXlncm91bmQuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTAzNzIyMDY5NjYyMDAwODgyNTMzIiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9naXRodWJjaWNkdGVzdGUlNDBhdmVudWVjb2RlLXBsYXlncm91bmQuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iCn0K
        project_id: avenuecode-playground
        export_default_credentials: True
    
    - name: Deploy
      run: |-
        gsutil -m rsync -R ./scripts-spark gs://spark_streaming_kafka_bq/dag_airflow
    
